### ISSUE TITLE
Errors from EPUB validator 3.0 (Metadata)

### ISSUE THREAD

**Issue by bobbytung** [ChineseCubes/react-odp#13]
1. Mimetype, Meta-inf should be the first in the archive.
2. [x] Move contents files to a folder (oebps)
3. [x] rootfile Full-path to the folder
4. Delete not frequently used dublin core in metadata,
   i.e. dc:contributor, dc:coverage, dc:relation, dc:source, dc:subject.
5. cover image 
6. [x] metadata : meta name="coverimage_id" content="cover-image" /
7. [x] manifest : add properties="cover-image" to cover image
8. dcterms: modified ss.sssZ -> ssZ
9. TOC.xhtml should not be declared as scripted
10. Add TTF manifest: 
    
    ```
    <item href="fonts/Noto-Light-Subset.ttf" id="fonts-Noto-Light-Subset-ttf" media-type="application/x-font-ttf"/>
    <item href="fonts/Noto-Normal-Subset.ttf" id="fonts-Noto-Normal-Subset-ttf" media-type="application/x-font-ttf"/>
    <item href="fonts/Noto-Bold-Subset.ttf" id="fonts-Noto-Bold-Subset-ttf" media-type="application/x-font-ttf"/>
    <item href="fonts/Noto-ExtraLight-Subset.ttf" id="fonts-Noto-ExtraLight-Subset-ttf" media-type="application/x-font-ttf"/>
    <item href="fonts/Noto-Heavy-Subset.ttf" id="fonts-Noto-Heavy-Subset-ttf" media-type="application/x-font-ttf"/>
    <item href="fonts/Noto-Regular-Subset.ttf" id="fonts-Noto-Regular-Subset-ttf" media-type="application/x-font-ttf"/>
    <item href="fonts/Noto-Medium-Subset.ttf" id="fonts-Noto-Medium-Subset-ttf" media-type="application/x-font-ttf"/>
    ```

**Comment by caasi** [comment]
NTS: how to fix "mimetype entry missing or not the first in archive": http://www.mobileread.com/forums/showthread.php?t=58913

**Comment by caasi** [comment]
Jush fix #14 at 8aa18de.

It passed the `EPUB-Checker`, would you please check it again?
https://github.com/ChineseCubes/react-odp/blob/structure-1/two-tigers.epub

**Comment by bobbytung** [comment]
EPUB Validator find no error but there's no cover image.

Actually we can ignore:
- [x] metadata : meta name="coverimage_id" content="cover-image" /

But have to add "properties="cover-image" to assign cover picture, And cover usually the first page of the slide? or will we upload separately?
- [ ] manifest : add properties="cover-image" to cover image

**Comment by caasi** [comment]
If the cover image can have any ratio, I can use the image from page1.

**Comment by bobbytung** [comment]
Sure, just do it.

WANDERER Bobby Tung
Sent from my iPhone.
