### ISSUE TITLE
Position size error on iBooks iOS App

### ISSUE THREAD

**Issue by bobbytung** [ChineseCubes/react-odp#16]
Thing look like [this](https://www.dropbox.com/s/3q4isd7mw830vlq/reactodp.mov?dl=0).

I think its div size in cm matter. 

It's a viewport issue, in line 8:

```
<meta name="viewport" content="width=1024, height=768, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1"></meta>
```

do nothing about scale to 

```
<meta name="viewport" content="width=1024, height=768"></meta>
```

It will fix.

**Comment by caasi** [comment]
fixed at 03b67ce
